npx esbuild ./index.js --bundle --platform=node --outfile=../../dist/hexo-admin-ehc.js
npx esbuild ./dist/hexo --bundle --platform=node --outfile=../../dist/hexo-cli.js
npx esbuild ./index.js --bundle --platform=node --outfile=../../dist/hexo-admin-ehc.js
npx esbuild ./index.js --bundle --platform=node --outfile=../../dist/hexo-admin-ehc.js
npx esbuild ./dist/hexo --bundle --platform=node --outfile=../../dist/hexo-cli.js
npx esbuild ./lib/front_matter --bundle --platform=node --outfile=../../dist/hexo-front-matter.js
npx esbuild ./lib/fs --bundle --platform=node --outfile=../../dist/hexo-fs.js
npx esbuild ./index.js --bundle --platform=node --outfile=../../dist/hexo-admin-ehc.js
npx esbuild ./dist/hexo --bundle --platform=node --outfile=../../dist/hexo-cli.js
npx esbuild ./lib/front_matter --bundle --platform=node --outfile=../../dist/hexo-front-matter.js
npx esbuild ./lib/fs --bundle --platform=node --outfile=../../dist/hexo-fs.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-archive.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-category.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-index.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-search.js
