npx esbuild ./index.js --bundle --platform=node --outfile=../../dist/hexo-admin-ehc.js
npx esbuild ./dist/hexo --bundle --platform=node --outfile=../../dist/hexo-cli.js
npx esbuild ./index.js --bundle --platform=node --outfile=../../dist/hexo-admin-ehc.js
npx esbuild ./index.js --bundle --platform=node --outfile=../../dist/hexo-admin-ehc.js
npx esbuild ./dist/hexo --bundle --platform=node --outfile=../../dist/hexo-cli.js
npx esbuild ./lib/front_matter --bundle --platform=node --outfile=../../dist/hexo-front-matter.js
npx esbuild ./lib/fs --bundle --platform=node --outfile=../../dist/hexo-fs.js
npx esbuild ./index.js --bundle --platform=node --outfile=../../dist/hexo-admin-ehc.js
npx esbuild ./dist/hexo --bundle --platform=node --outfile=../../dist/hexo-cli.js
npx esbuild ./lib/front_matter --bundle --platform=node --outfile=../../dist/hexo-front-matter.js
npx esbuild ./lib/fs --bundle --platform=node --outfile=../../dist/hexo-fs.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-archive.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-category.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-index.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-search.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-tag.js
npx esbuild ./dist/i18n.js --bundle --platform=node --outfile=../../dist/hexo-i18n.js
npx esbuild ./dist/log.js --bundle --platform=node --outfile=../../dist/hexo-log.js
npx esbuild ./lib/pagination --bundle --platform=node --outfile=../../dist/hexo-pagination.js
npx esbuild ./index.js --bundle --platform=node --outfile=../../dist/hexo-recommended-posts.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-renderer-ejs.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-renderer-marked.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-renderer-stylus.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-server.js
npx esbuild ./lib/index --bundle --platform=node --outfile=../../dist/hexo-util.js
npx esbuild ./index.js --bundle --platform=node --outfile=../../dist/hexo-admin-ehc.js
npx esbuild ./dist/hexo --bundle --platform=node --outfile=../../dist/hexo-cli.js
npx esbuild ./lib/front_matter --bundle --platform=node --outfile=../../dist/hexo-front-matter.js
npx esbuild ./lib/fs --bundle --platform=node --outfile=../../dist/hexo-fs.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-archive.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-category.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-index.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-search.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-tag.js
npx esbuild ./dist/i18n.js --bundle --platform=node --outfile=../../dist/hexo-i18n.js
npx esbuild ./dist/log.js --bundle --platform=node --outfile=../../dist/hexo-log.js
npx esbuild ./lib/pagination --bundle --platform=node --outfile=../../dist/hexo-pagination.js
npx esbuild ./index.js --bundle --platform=node --outfile=../../dist/hexo-recommended-posts.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-renderer-ejs.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-renderer-marked.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-renderer-stylus.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-server.js
npx esbuild ./lib/index --bundle --platform=node --outfile=../../dist/hexo-util.js
npx esbuild ./index.js --bundle --platform=node --outfile=../../dist/hexo-admin-ehc.js
npx esbuild ./dist/hexo --bundle --platform=node --outfile=../../dist/hexo-cli.js
npx esbuild ./lib/front_matter --bundle --platform=node --outfile=../../dist/hexo-front-matter.js
npx esbuild ./lib/fs --bundle --platform=node --outfile=../../dist/hexo-fs.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-archive.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-category.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-index.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-search.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-tag.js
npx esbuild ./dist/i18n.js --bundle --platform=node --outfile=../../dist/hexo-i18n.js
npx esbuild ./dist/log.js --bundle --platform=node --outfile=../../dist/hexo-log.js
npx esbuild ./lib/pagination --bundle --platform=node --outfile=../../dist/hexo-pagination.js
npx esbuild ./index.js --bundle --platform=node --outfile=../../dist/hexo-recommended-posts.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-renderer-ejs.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-renderer-marked.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-renderer-stylus.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-server.js
npx esbuild ./lib/index --bundle --platform=node --outfile=../../dist/hexo-util.js
npx esbuild ./index.js --bundle --platform=node --outfile=../../dist/hexo-admin-ehc.js
npx esbuild ./dist/hexo --bundle --platform=node --outfile=../../dist/hexo-cli.js
npx esbuild ./lib/front_matter --bundle --platform=node --outfile=../../dist/hexo-front-matter.js
npx esbuild ./lib/fs --bundle --platform=node --outfile=../../dist/hexo-fs.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-archive.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-category.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-index.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-search.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-tag.js
npx esbuild ./dist/i18n.js --bundle --platform=node --outfile=../../dist/hexo-i18n.js
npx esbuild ./dist/log.js --bundle --platform=node --outfile=../../dist/hexo-log.js
npx esbuild ./lib/pagination --bundle --platform=node --outfile=../../dist/hexo-pagination.js
npx esbuild ./index.js --bundle --platform=node --outfile=../../dist/hexo-recommended-posts.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-renderer-ejs.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-renderer-marked.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-renderer-stylus.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-server.js
npx esbuild ./lib/index --bundle --platform=node --outfile=../../dist/hexo-util.js
npx esbuild ./index.js --bundle --platform=node --outfile=../../dist/hexo-admin-ehc.js
npx esbuild ./dist/hexo --bundle --platform=node --outfile=../../dist/hexo-cli.js
npx esbuild ./lib/front_matter --bundle --platform=node --outfile=../../dist/hexo-front-matter.js
npx esbuild ./lib/fs --bundle --platform=node --outfile=../../dist/hexo-fs.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-archive.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-category.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-index.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-search.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-tag.js
npx esbuild ./dist/i18n.js --bundle --platform=node --outfile=../../dist/hexo-i18n.js
npx esbuild ./dist/log.js --bundle --platform=node --outfile=../../dist/hexo-log.js
npx esbuild ./lib/pagination --bundle --platform=node --outfile=../../dist/hexo-pagination.js
npx esbuild ./index.js --bundle --platform=node --outfile=../../dist/hexo-recommended-posts.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-renderer-ejs.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-renderer-marked.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-renderer-stylus.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-server.js
npx esbuild ./lib/index --bundle --platform=node --outfile=../../dist/hexo-util.js
npx esbuild ./index.js --bundle --platform=node --outfile=../../dist/hexo-admin-ehc.js
npx esbuild ./dist/hexo --bundle --platform=node --outfile=../../dist/hexo-cli.js
npx esbuild ./lib/front_matter --bundle --platform=node --outfile=../../dist/hexo-front-matter.js
npx esbuild ./lib/fs --bundle --platform=node --outfile=../../dist/hexo-fs.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-archive.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-category.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-index.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-search.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-generator-tag.js
npx esbuild ./dist/i18n.js --bundle --platform=node --outfile=../../dist/hexo-i18n.js
npx esbuild ./dist/log.js --bundle --platform=node --outfile=../../dist/hexo-log.js
npx esbuild ./lib/pagination --bundle --platform=node --outfile=../../dist/hexo-pagination.js
npx esbuild ./index.js --bundle --platform=node --outfile=../../dist/hexo-recommended-posts.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-renderer-ejs.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-renderer-marked.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-renderer-stylus.js
npx esbuild ./index --bundle --platform=node --outfile=../../dist/hexo-server.js
npx esbuild ./lib/index --bundle --platform=node --outfile=../../dist/hexo-util.js
npx esbuild ./index.js --bundle --platform=node --outfile=../../dist/hexo-admin-ehc.js
npx esbuild ./dist/hexo --bundle --platform=node --outfile=../../dist/hexo-cli.js
npx esbuild ./lib/front_matter --bundle --platform=node --outfile=../../dist/hexo-front-matter.js
